Features<-read.table("./features.txt")
subjTest<-read.table("./subject_test.txt")
subjTrain<-read.table("./subject_train.txt")
Xtest<-read.table("./X_test.txt")
Ytest<-read.table("./y_test.txt")
Xtrain<-read.table("./X_train.txt")
Ytrain<-read.table("./y_train.txt")
Activity<-read.table("./activity_labels.txt")
Activity$V2<-tolower(Activity$V2)
Activity$V2<-gsub("_u","U",Activity$V2)
Activity$V2<-gsub("_d","D",Activity$V2)
YtestAct<-sub("1",Activity[1,2],Ytest$V1)
YtestAct<-sub("2",Activity[2,2],YtestAct)
YtestAct<-sub("3",Activity[3,2],YtestAct)
YtestAct<-sub("4",Activity[4,2],YtestAct)
YtestAct<-sub("5",Activity[5,2],YtestAct)
YtestAct<-sub("6",Activity[6,2],YtestAct)
YtrainAct<-sub("1",Activity[1,2],Ytrain$V1)
YtrainAct<-sub("2",Activity[2,2],YtrainAct)
YtrainAct<-sub("3",Activity[3,2],YtrainAct)
YtrainAct<-sub("4",Activity[4,2],YtrainAct)
YtrainAct<-sub("5",Activity[5,2],YtrainAct)
YtrainAct<-sub("6",Activity[6,2],YtrainAct)
Ytest$Activity<-YtestAct
Ytrain$Activity<-YtrainAct
Features$V2<-gsub("^t|\\(t","Time",Features$V2)
Features$V2<-gsub("^f|\\(f","Frequency",Features$V2)
Features$V2<-gsub("Acc","Accelerometer",Features$V2)
Features$V2<-gsub("Gyro","Gyroscope",Features$V2)
Features$V2<-gsub("Mag","Magnitude",Features$V2)
Features$V2<-gsub("mean","Mean",Features$V2)
Features$V2<-gsub("std","StandardDeviation",Features$V2)
Features$V2<-gsub("BodyBody","Body",Features$V2)
Features$V2<-gsub("-(.*)\\()-?(.*)|-(.*)-?(.*)","\\1\\2",Features$V2)
Features$V2<-gsub("([a-zA-Z]),([0-9])","\\1at\\2",Features$V2)
Features$V2<-gsub("([a-zA-Z])\\)?,([a-zA-Z])","\\1by\\2",Features$V2)
Features$V2<-gsub("([0-9]+),([0-9]+)","\\1to\\2",Features$V2)
Features$V2<-gsub("\\(|\\)$","",Features$V2)
colnames(Xtest)<-Features$V2
colnames(Xtrain)<-Features$V2
Xtest$Subject<-subjTest[,1]
Xtrain$Subject<-subjTrain[,1]
names(Xtest$Subject)<-"Subject"
names(Xtrain$Subject)<-"Subject"
Xtest$SubjectType<-c(rep("test",nrow(Xtest)))
Xtrain$SubjectType<-c(rep("train",nrow(Xtrain)))
names(Xtest$SubjectType)<-"SubjectType"
names(Xtrain$SubjectType)<-"SubjectType"
Xtest$Activity<-Ytest$Activity
Xtrain$Activity<-Ytrain$Activity
names(Xtest$Activity)<-"Activity"
names(Xtrain$Activity)<-"Activity"
MergeCols<-grep("Mean|StandardDeviation|Subject|Activity",names(Xtest))
Merged<-rbind(Xtest[,MergeCols],Xtrain[,MergeCols])
myTidySet<-aggregate(Merged[,1:79],list(Merged$Subject,Merged$Activity),FUN=mean)
names(myTidySet)[1]<-"Subject"
names(myTidySet)[2]<-"Activity"
myTidySet<-myTidySet[order(myTidySet$Subject),]
write.table(myTidySet,row.names = FALSE,file="myTidySet.txt")